name: Build Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "35 2 * * *"
  pull_request:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v6
      - name: Run the build
        run: |
          export DATE=$(date +%Y%m%d)
          # use that here since the variable are not present before start, so can't be in env
          export LOGIN=$GITHUB_REPOSITORY_OWNER
          export IMAGE=$LOGIN/bootc

          docker build . --tag $REGISTRY/$IMAGE:$DATE --tag $REGISTRY/$IMAGE:latest
          if [[ ${GITHUB_REF} == 'refs/heads/main' &&  ${GITHUB_EVENT_NAME} == 'push' ]] || [[ ${GITHUB_EVENT_NAME} == 'schedule' ]]; then
            echo $PASSWORD | docker login $REGISTRY -u $LOGIN --password-stdin
            docker push $REGISTRY/$IMAGE:latest
            docker push $REGISTRY/$IMAGE:$DATE
          fi;
        env:
          REGISTRY: ghcr.io
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}

